---

- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - shell: "touch /root/worked"
    - shell: "curl -sSL https://get.docker.com/ | sh"
    - service:
        name: docker
        state: started
    - user:
        name: adminomc
        groups: docker

