---

- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - include: tasks/install-docker.yml
    - uri:
        method: GET
        url: http://169.254.169.254/openstack/latest/meta_data.json
        status_code: 200
        return_content: yes
      register: metadata
    - shell: docker swarm init --advertise-addr eth0
    - shell: docker swarm join-token manager | grep ':2377' | sed 's/ *//g'
      register: manager
    - shell: docker swarm join-token manager --quiet
      register: manager_token
    - shell: docker swarm join-token worker --quiet
      register: worker_token

    - uri:
        method: PUT
        url: "http://{{ metadata.json.meta.etcd_cluster }}/v2/keys/{{ metadata.json.meta.swarm_cluster_id }}/worker_token"
        status_code: 200,201
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: value={{worker_token.stdout}}
    - uri:
        method: PUT
        url: "http://{{ metadata.json.meta.etcd_cluster }}/v2/keys/{{ metadata.json.meta.swarm_cluster_id }}/manager_token"
        status_code: 200,201
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: value={{manager_token.stdout}}
    - uri:
        method: PUT
        url: "http://{{ metadata.json.meta.etcd_cluster }}/v2/keys/{{ metadata.json.meta.swarm_cluster_id }}/manager"
        status_code: 200,201
        HEADER_Content-Type: "application/x-www-form-urlencoded"
        body: value={{manager.stdout}}

