---

heat_template_version: 2015-04-30

description: Auto scaling app

parameters:
  number_of_worker:
    type: number
    label: Number of worker
    default: 3
  node_flavor:
    type: string
    label: Node flavor
    default: t1.tiny.small-2
  node_key:
    type: string
    label: Node ssh Key
    default: ael
  node_image:
    type: string
    label: Node image
    default: "Ubuntu 16.04 Xenial Cloud (kvm)"
  network:
    type: string
    label: Network name
    default: internal-run
  etcd_cluster:
    type: string
    description: Hostnames of etcd clusters nodes

resources:
  setup_node:
    type: OS::Heat::SoftwareConfig
    properties:
      config: |
        #!/bin/sh
        chage -d '' adminomc
        echo '172.23.102.7 repository.services.rhone.zmhg' >> /etc/hosts
        sed -i 's/nameserver.*/nameserver 8.8.8.8/' /etc/resolv.conf
        apt-get update
        apt-get install -y ansible jq
        ansible-pull -i 'localhost' -U https://github.com/ael-g/openstack-autoscaling.git $(curl http://169.254.169.254/openstack/latest/meta_data.json | jq --raw-output '.meta["ansible-playbook"]')

  swarm_cluster_id:
    type: OS::Heat::RandomString
    properties:
      length: 32

  cluster_manager:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          name: manager%index%
          key_name: {get_param: node_key}
          flavor: {get_param: node_flavor}
          image: {get_param: node_image}
          user_data_format: RAW
          user_data: {get_resource: setup_node}
          metadata: {
            ansible-playbook: 'manager.yml', 
            swarm_cluster_id: {get_attr: [swarm_cluster_id, value]},
            etcd_cluster: {get_param: etcd_cluster}
          }
          networks:
            - network: {get_param: network}

  cluster_worker:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: number_of_worker}
      resource_def:
        type: OS::Nova::Server
        properties:
          name: worker%index%
          key_name: {get_param: node_key}
          flavor: {get_param: node_flavor}
          image: {get_param: node_image}
          user_data_format: RAW
          user_data: {get_resource: setup_node}
          metadata: {
            ansible-playbook: 'manager.yml', 
            swarm_cluster_id: {get_attr: [swarm_cluster_id, value]},
            etcd_cluster: {get_param: etcd_cluster}
          }
          networks:
            - network: {get_param: network}

outputs:
  swarm_cluster_id:
    description: Id for swarm key in etcd cluster
    value: {get_param: [swarm_cluster_id, value]}
