---

- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - include: tasks/install-docker.yml
    - uri:
        method: GET
        url: http://169.254.169.254/openstack/latest/meta_data.json
        status_code: 200
        return_content: yes
      register: metadata
    - command: curl -I http://{{metadata.json.meta.etcd_cluster}}/v2/keys/{{metadata.json.meta.swarm_cluster_id}}
      register: result
      until: result.stdout.find("200 OK") != -1
      retries: 12
      delay: 3
      changed_when: false

    - uri:
        method: GET
        url: http://{{metadata.json.meta.etcd_cluster}}/v2/keys/{{metadata.json.meta.swarm_cluster_id}}
        return_content: yes
      register: swarm-cluster
    - shell: docker swarm
