---

- hosts: localhost
  connection: local
  gather_facts: yes

  tasks:
    - include: tasks/install-docker.yml
    - uri:
        method: GET
        url: http://169.254.169.254/openstack/latest/meta_data.json
        status_code: 200
        return_content: yes
      register: metadata
    - uri:
        method: GET
        url: http://{{metadata.json.meta.etcd_cluster}}/v2/keys/{{metadata.json.meta.swarm_cluster_id}}/worker_token
        return_content: yes
      register: worker_token
    - uri:
        method: GET
        url: http://{{metadata.json.meta.etcd_cluster}}/v2/keys/{{metadata.json.meta.swarm_cluster_id}}/manager
        return_content: yes
      register: manager
    - shell: docker swarm join {{manager.json.node.value}} --token {{worker_token.json.node.value}}
